services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    image: python:3.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "8000:8000"
    working_dir: /app
    command: >
      sh -c "
      pip install -r requirements.txt &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      echo \"from django.contrib.auth import get_user_model; User = get_user_model(); \
      User.objects.create_superuser( \
        '${DJANGO_SUPERUSER_USERNAME}', \
        '${DJANGO_SUPERUSER_EMAIL}', \
        '${DJANGO_SUPERUSER_PASSWORD}' \
      ) if not User.objects.filter(username='${DJANGO_SUPERUSER_USERNAME}').exists() else print('Superuser already exists')\" \
      | python manage.py shell &&
      gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
      "
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static 
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  mysql_data:
